### PR TITLE
full working support of windows system

### PR DESCRIPTION
**Pull request by oupala**
The real support of windows system needs another modification. Sorry for not having seen that on the first pull request.

### CODE REVIEW

**Comment by oupala** [comment]
@christophercliff The previous pull request was actually not working on windows.

This pull request aims at fixing this lack definetly.

**Comment by oupala** [comment]
@christophercliff do you have an opinion on the pull request?

**Comment by oupala** [comment]
@christophercliff is there a problem with my pull request?

I'm ok to modify my pull request if you give me some clues.

**Comment by christophercliff** [comment]
Is there a way to verify this fix with automated testing? I don't want a repeat of https://github.com/christophercliff/metalsmith-fingerprint/issues/7.

**Comment by oupala** [comment]
Hello @christophercliff I have to apologize for having asked you so much. In fact, I read my test result in a wrong way and it appears that #7 **is working**.

My test cases shows that **it works on linux but not on windows**. But what I had to read and understand from the previous sentence, is that **the linux syntax work on windows but the old-wordkaround-windows-syntax do not work any more on windows**. And that's a good thing that the old-wordkaround-windows-syntax is no more necessary on windows, and that we can now use the **standard** *linux* syntaxt.

Thanks, and sorry for the inconvenience.

The last missing feature that prevents me from using this plugin is #10

**Comment by oupala** [comment]
In fact, #7 does not work.

**Pull request closed without merging**
